del /S /Q *.a
del /S /Q *.aps
del /S /Q *.bsc
del /S /Q *.dll
del /S /Q *.dsw
del /S /Q *.exe
del /S /Q *.idb
del /S /Q *.ilc
del /S /Q *.ild
del /S /Q *.ilf
del /S /Q *.ilk
del /S /Q *.ils
del /S /Q *.map
del /S /Q *.ncb
del /S /Q *.obj
del /S /Q *.o
del /S /Q *.opt
del /S /Q *.pdb
del /S /Q *.plg
del /S /Q *.res
del /S /Q *.sbr
del /S /Q *.tds
